### ISSUE TITLE
What is this plugin actually doing?

### ISSUE THREAD

**Issue by m7ess5** [IWAtech/yourls-referrer-plugin#1]
hi, i have installed this plugin but i could not find anything new.

can you please explain what is to be expected from this plugin ??

thanks

**Comment by kl4n4** [comment]
hi, this is just an plugin that was used internally by us and in it's current form it is not really usable for any other use cases (mainly since it is bound to the updatemi.com domain).
essentially we use this plugin to add special query params to the resolved url based on the referrer. e.g.: when the code resolves to an updatemi.com domain and the referrer is either facebook.com or twitter.com it will set a query param `pk_campaign` (Piwik Campaign).
